namePrefix: dev-
namespace: dev
bases:
  - ../../base
imageTags:
  - name: mhussain78/tekton-greeting-service
    newTag: a0d86f28e964947933757c41f47bfbc62a6fb39d
patchesStrategicMerge:
  - deployment-patch.yaml