namePrefix: dev-
namespace: dev
bases:
  - ../../base
imageTags:
  - name: mhussain78/tekton-greeting-service
    newTag: 3f21d3985884698ff09a2609f437305c1c684321
patchesStrategicMerge:
  - deployment-patch.yaml