apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tekton-greeting-service
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - overlay: dev
        gitRepo: git@github.com:mhussain78/tekton-greeting-service.git ### https://github.com/dinushchathurya/tekton-manifest.git
        appPath: tekton-greeting-service/overlays
        appBranch: master
      - overlay: prod
        gitRepo: git@github.com:mhussain78/tekton-greeting-service.git ### https://github.com/dinushchathurya/tekton-manifest.git
        appPath: tekton-greeting-service/overlays
        appBranch: master
  template:
    metadata:
      name: 'tekton-greeting-service-{{overlay}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PruneLast=true
          - Validate=false
          - CreateNamespace=true
      source:
        repoURL: '{{gitRepo}}'
        targetRevision: '{{appBranch}}'
        path: '{{appPath}}/{{overlay}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'tekton-greeting-service{{overlay}}'